//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IdDetalleFactura { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdCita { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdPersonaCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdPersonaEmpleado { get; set; }
        public Nullable<int> IdServicio { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
